version: '2'
services:
 app:
  image: "node:12.18-alpine3.12"
  container_name: "darkarts"
  working_dir: /home/node/app
  volumes: 
   - ./:/home/node/app
  environment:
   - NODE_ENV=development
  ports: 
   - "3000:3000"
  command: "npm start"